### ISSUE TITLE
Tcolorbox theorems

### ISSUE THREAD

**Issue by Lads-oxygen** [sleepymalc/LaTeX-Template#1]
Hi there,

I just wanted to let you know that I have adapted your template (thank you for providing it freely) to use the `tcolorbox` package for theorem environments. I have made other changes but I thought that this tcolorbox implementation may be of interest to you.

You can find the repository link and view the pdf [here](https://lads-oxygen.github.io/).

Here is a preview:
![image](https://gcdnb.pbrd.co/images/wQGPo3VhjNMM.png?o=1)

**Comment by sleepymalc** [comment]
Oh, I somehow miss the issue. Yes, actually I'm thinking about switching to tcolorbox, will definitely take a look. I'll let you know how it goes after I tried this.

**Comment by sleepymalc** [comment]
Actually I just realized that since if changes to `tcolorbox`, all the title, labeling, and other stuffs needs to be changed as well, which is a bit too much for me to do the change currently. But again thanks for the implementation!
