### ISSUE TITLE
No lecture in the header on the last page

### ISSUE THREAD

**Issue by LuckeeDev** [sleepymalc/LaTeX-Template#2]
Hi! First of all, thank you for this amazing template. I'm trying to use it for some of my notes and I noticed that the lecture tag disappears from the header of the last page. I noticed this behavior applies to your [Notes](https://github.com/sleepymalc/Notes) as well. Do you have any idea why it might be like this? Do you know of any solution?

**Comment by sleepymalc** [comment]
It's probably related to how `\@lecture` is defined:
```latex
\def\@lecture{}%
\newcommand{\lecture}[3]{
    \ifthenelse{\isempty{#3}}{%
        \def\@lecture{Lecture #1}%
    }{%
        \def\@lecture{Lecture #1: #3}%
    }%
    \section*{\@lecture}
    \marginpar{\small\textsf{\mbox{#2}}}
}
```
I don't have a good solution though. I just leave it as it is, but like to see a fix.

**Comment by LuckeeDev** [comment]
For some weird reason, adding `\global` before `\def` fixes the issue for me.

```
\global\def\@lecture{Lecture #1: #3}
```
